const AgentData = [
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
  {
    Agent_name: "James Adekola",
    Agent_ID: "N123456",
    Phone_Number: "406-633-2320",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: true,
  },
  {
    Agent_name: "Shola Adeniyi",
    Agent_ID: "N123456",
    Phone_Number: "490-807-5271",
    Business_Name: "TM30 GLOBAL INTERNATIONAL",
    Email_Address: "CUSTOMER@TM30.COM",
    State: "LAGOS STATE",
    Status: false,
  },
];

export default AgentData;
