const data = [
  {
    Agent_name: "Tamarah Fydoe",
    Agent_ID: "com.marketwatch.Overhold",
    Phone_Number: "406-633-2320",
    Business_Name: "Gabspot",
    Email_Address: "tfydoe0@senate.gov",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Madlin Hubbis",
    Agent_ID: "com.kickstarter.Span",
    Phone_Number: "490-807-5271",
    Business_Name: "Dazzlesphere",
    Email_Address: "mhubbis1@squidoo.com",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Jasper Garwill",
    Agent_ID: "gov.usgs.Overhold",
    Phone_Number: "137-714-5772",
    Business_Name: "Blogtags",
    Email_Address: "jgarwill2@t-online.de",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Daisey Densey",
    Agent_ID: "com.eepurl.Hatity",
    Phone_Number: "635-633-6001",
    Business_Name: "Eazzy",
    Email_Address: "ddensey3@google.nl",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Ashlen Gallant",
    Agent_ID: "com.deviantart.Fixflex",
    Phone_Number: "823-435-8266",
    Business_Name: "Flashset",
    Email_Address: "agallant4@github.io",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Sally Lazenbury",
    Agent_ID: "gl.goo.Tampflex",
    Phone_Number: "917-441-8131",
    Business_Name: "Viva",
    Email_Address: "slazenbury6@npr.org",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Ashlen Gallant",
    Agent_ID: "com.deviantart.Fixflex",
    Phone_Number: "823-435-8266",
    Business_Name: "Flashset",
    Email_Address: "agallant4@github.io",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Sally Lazenbury",
    Agent_ID: "gl.goo.Tampflex",
    Phone_Number: "917-441-8131",
    Business_Name: "Viva",
    Email_Address: "slazenbury6@npr.org",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Madlin Hubbis",
    Agent_ID: "com.kickstarter.Span",
    Phone_Number: "490-807-5271",
    Business_Name: "Dazzlesphere",
    Email_Address: "mhubbis1@squidoo.com",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Jasper Garwill",
    Agent_ID: "gov.usgs.Overhold",
    Phone_Number: "137-714-5772",
    Business_Name: "Blogtags",
    Email_Address: "jgarwill2@t-online.de",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Daisey Densey",
    Agent_ID: "com.eepurl.Hatity",
    Phone_Number: "635-633-6001",
    Business_Name: "Eazzy",
    Email_Address: "ddensey3@google.nl",
    State: "New York",
    Status: true,
  },
  {
    Agent_name: "Ashlen Gallant",
    Agent_ID: "com.deviantart.Fixflex",
    Phone_Number: "823-435-8266",
    Business_Name: "Flashset",
    Email_Address: "agallant4@github.io",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Sally Lazenbury",
    Agent_ID: "gl.goo.Tampflex",
    Phone_Number: "917-441-8131",
    Business_Name: "Viva",
    Email_Address: "slazenbury6@npr.org",
    State: "New York",
    Status: false,
  },
  {
    Agent_name: "Ashlen Gallant",
    Agent_ID: "com.deviantart.Fixflex",
    Phone_Number: "823-435-8266",
    Business_Name: "Flashset",
    Email_Address: "agallant4@github.io",
    State: "New York",
    Status: false,
  },
];

export default data;
