const RentalData = [
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: true,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "James Adekola",
    Terminal_ID: "N123456",
    Terminal_Location: "OGBA, LAGOS STATE",
    resp_code: "10",
    Status: "SUCESSFUL",
    Flag_Unflag: false,
    Exempt_agent: true,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
  {
    Assigned_Agent: "Shola Adeniyi",
    Terminal_ID: "N123456",
    Terminal_Location: "IKEJA, LAGOS STATE",
    resp_code: "20",
    Status: "FAILED",
    Flag_Unflag: false,
    Exempt_agent: false,
    Grant_sucession: "Click to Set Sucession",
    Place_lien: true,
  },
];

export default RentalData;
